name: attendance_monitoring_system
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  mongo_dart: ^0.9.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  qr_code_scanner: ^1.0.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
